pub(crate) mod character;
pub(crate) mod chat_dialog;
pub(crate) mod codex_dialog;
pub(crate) mod death_dialog;
pub(crate) mod help_dialog;
pub(crate) mod hud;
pub(crate) mod inspect_dialog;
pub(crate) mod quest_complete_dialog;
pub(crate) mod time_widget;
