[package]
name = "tales_of_kathay"
version = "0.0.15"
edition = "2021"

[dependencies]
noise = "0.9.0"
piston = "1.0.0"
piston2d-graphics = "0.45.0"
#piston2d-opengl_graphics = "0.89.0"
piston2d-opengl_graphics = { path = "../opengl_graphics" }
pistoncore-sdl2_window = "0.71.0"
image = "0.25.5"
rodio = "0.20.1"
toml = "0.8.22"
regex = "1.11.1"
flamegraph = "0.6.8"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
