[package]
name = "tales_of_kathay"
version = "0.0.13"
edition = "2021"

[dependencies]
noise = "0.9.0"
piston = "1.0.0"
piston2d-graphics = "0.45.0"
piston2d-opengl_graphics = "0.89.0"
pistoncore-sdl2_window = "0.71.0"
image = "0.25.5"
rodio = "0.20.1"
toml = "0.8.22"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
