[symbols]
'b' = { ground= 1, object= 10 }
'r' = { ground= 1, object= 8 }
'c' = { ground= 4, object= 5 }
't' = { ground= 4, object= 4 }

[camp_start]

[camp_start.a]
size = [7, 7]
template = """
.......
.......
...r...
....b..
.......
.......
......."""

[camp_start.b]
size = [7, 7]
template = """
.......
.......
.......
...b...
....tc.
.......
......."""

[camp_start.c]
size = [4, 4]
template = """
....
.b..
....
....
"""