[symbols]
'b' = { ground= "tile:grass_patchy", object= "obj:tent" }
'r' = { ground= "tile:grass_patchy", object= "obj:barrel" }
'c' = { ground= "tile:grass_patchy", object= "obj:stool" }
't' = { ground= "tile:grass_patchy", object= "obj:table" }
'+' = { ground= "tile:grass_patchy" }

[camp_start]

[camp_start.a]
size = [7, 7]
template = """
.......
...+...
..+r+..
..++b..
...+...
.......
......."""

[camp_start.b]
size = [7, 7]
template = """
.......
.......
.......
...b...
...+tc.
..+....
......."""

[camp_start.c]
size = [4, 4]
template = """
....
.b..
.+..
....
"""