[symbols]
'b' = { ground= "tile:grass_patchy", object= "obj:tent" }
'r' = { ground= "tile:grass_patchy", object= "obj:barrel" }
'c' = { ground= "tile:grass_patchy", object= "obj:stool" }
't' = { ground= "tile:grass_patchy", object= "obj:table" }
'1' = { ground= "tile:grass", spawn_point = true }
'+' = { ground= "tile:grass_patchy" }

[camp_start]

[camp_start.a]
size = [7, 7]
template = """
.......
1..+.1.
..+r+..
..++b..
...+1..
.1.....
.....1."""
