[symbols]
'-' = { ground= 8, object= 0 }
'b' = { ground= 8, object= 13 }
'#' = { ground= 8, object= 15 }
'u' = { ground= 8, object= 17 }
'd' = { ground= 1, object= 16 }
'M' = { ground= 8, object= 0, connect = "varningr_lair" }
'R' = { ground= 8, object= 0, connect = "varningr_room" }
'E' = { ground= 8, object= 0, connect = "varningr_entrance" }

[varningr_surface]
[varningr_surface.a]
size = [3, 3]
template = """
...
.d.
...
"""

[varningr_lair]

[varningr_lair.a]
size = [15, 15]
allow_rotate = true
template = """
.....#######...
....#########..
..####b----###.
.###--------##.
###---------##.
##----------##.
##-----b----##.
##----------##.
##----------##.
##----------##.
##-b--------##.
.###-------##..
..###---#####..
...##---##.....
...##-R-##.....
"""

[varningr_room]

[varningr_room.a]
size = [9, 9]
allow_rotate = true
template = """
..#-M-##.
.##----##
##------#
##b-----#
#-------#
#------b#
#------##
##-----##
.##-E-##.
"""

[varningr_room.b]
size = [7, 7]
allow_rotate = true
template = """
##-R-##
##----#
##-----
###---R
####---
#######
#######
"""

[varningr_room.c]
size = [9, 9]
allow_rotate = true
template = """
..#-R-##.
.##----##
##------#
##--#---#
#---#---#
#---#---#
#---#--##
##-----##
.##-R-##.
"""


[varningr_room.d]
size = [9, 9]
allow_flip_hor = true
allow_flip_ver = true
template = """
######-R#
######--#
#####---#
#####--##
####---##
##----###
#---#####
#--######
#R-######
"""

[varningr_entrance]

[varningr_entrance.a]
size = [5, 5]
allow_rotate = true
template = """
#-R-#
#---#
#-u-#
#b-##
#####
"""