[symbols]
'#' = { ground= 4, object= 1 }
'_' = { ground= 4 }
'+' = { ground= 5 }
'*' = { ground= 5, statue_spot= true }
'b' = { ground= 4, object= 3 }
'c' = { ground= 4, object= 5 }
't' = { ground= 4, object= 4 }
'r' = { ground= 1, object= 8 }
'&' = { path_endpoint = true }
'@' = { connect = "" }
'A' = { connect = "village_house_start" }
'B' = { connect = "village_house_room" }


[village_house_start]

[village_house_start.a]
size = [9, 8]
template = """
#########
#_______#
#_______B
#_ct____#
#__c____#
#_______#
##_######
..&..rr.."""

[village_house_start.b]
size = [9, 8]
template = """
#########
#_______#
#___ctc_#
B_______#
#_______#
#_______#
######_##
.r....&.."""

[village_house_start.d]
size = [9, 8]
template = """
#########
#_______#
#_______#
#_ct____#
#__c____#
#_______#
##_######
..&..rr.."""


[village_house_room]

[village_house_room.a]
size = [5, 5]
template = """
#####
#c_b#
A___#
#___#
#####"""

[village_house_room.b]
size = [5, 6]
template = """
######
#___b#
A___b#
#____#
######"""

[village_house_room.c]
size = [5, 5]
template = """
#####
#b__#
#c__A
#___#
#####"""

[village_house_room.d]
size = [5, 6]
template = """
######
#c__b#
#b___A
#____#
######"""

[village_plaza]
[village_plaza.d]
size = [9, 9]
template = """
..+++++..
.++*+*++.
++*+++*++
+*+++++*+
++++&++++
+*+++++*+
++*+++*++
.++*+*++.
..+++++.."""


[village_cemetery]
[village_cemetery.d]
size = [15, 15]
template = """
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""