[symbols]
'#' = { ground= "tile:floor", object= "obj:wall" }
'_' = { ground= "tile:floor" }
'+' = { ground= "tile:cobblestone" }
'*' = { ground= "tile:cobblestone", statue_spot= true }
'b' = { ground= "tile:floor", object= "obj:bed" }
'c' = { ground= "tile:floor", object= "obj:stool" }
't' = { ground= "tile:floor", object= "obj:table" }
'r' = { ground= "tile:grass", object= "obj:barrel" }
'd' = { ground= "tile:floor", object= "obj:barrel" }
'-' = { ground= "tile:carpet_red" }
'$' = { ground= "tile:floor", object= "obj:chair" }
'&' = { path_endpoint = true }
'A' = { ground= "tile:floor", connect = "village_house_start" }
'B' = { ground= "tile:floor", connect = "village_house_room" }


[village_house_start]

[village_house_start.a]
size = [8, 8]
allow_flip_hor = true
allow_flip_ver = true
template = """
........
.######.
.#ctc_#.
.#____B.
.#____#.
.#____#.
.##_###.
.r.&...."""

[village_house_start.b]
size = [9, 8]
allow_rotate=true
template = """
.........
.#######.
.#d__ct#.
.#_____#.
.#_____#.
.#_____#.
.##_####.
...&....."""

[village_house_ruler]
[village_house_ruler.a]
size = [9, 10]
template = """
.........
.#######.
.#__$__#.
.#_---_#.
.#_---_#.
.#_---_#.
.#_---_#.
.#_____#.
.###_###.
....&...."""

[village_house_room]

[village_house_room.a]
size = [5, 5]
template = """
#####
#c_b#
A___#
#___#
#####"""

[village_house_room.b]
size = [5, 6]
template = """
######
#___b#
A___b#
#____#
######"""

[village_house_room.c]
size = [5, 5]
template = """
#####
#b__#
#c__A
#___#
#####"""

[village_house_room.d]
size = [5, 6]
template = """
######
#c__b#
#b___A
#____#
######"""

[village_plaza]
[village_plaza.d]
size = [9, 9]
template = """
..+++++..
.++*+*++.
++*+++*++
+*+++++*+
++++&++++
+*+++++*+
++*+++*++
.++*+*++.
..+++++.."""


[village_cemetery]
[village_cemetery.d]
size = [15, 15]
template = """
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""