[symbols]
'#' = { ground= 4, object= 1 }
'_' = { ground= 4 }
'+' = { ground= 5 }
'*' = { ground= 5, statue_spot= true }
'b' = { ground= 4, object= 3 }
'c' = { ground= 4, object= 5 }
't' = { ground= 4, object= 4 }
'r' = { ground= 1, object= 8 }
'&' = { path_endpoint = true }
'@' = { connect = "" }
'A' = { connect = "village_house_start" }
'B' = { connect = "village_house_room" }


[village_house_start]

[village_house_start.a]
size = [5, 6]
template = """
#####
#t__#
#c__B
#___#
##_##
..&.r"""

[village_house_start.b]
size = [7, 6]
template = """
#######
#b__ct#
#____c#
#_____#
###_###
.r.&..."""

[village_house_start.c]
size = [6, 6]
template = """
#####.
#_ct#.
B___#r
#___#.
##_##.
..&..."""

[village_house_start.d]
size = [5, 6]
template = """
#####
B_ct#
#___#
#t__B
##_##
..&.."""

[village_house_room]

[village_house_room.a]
size = [4, 4]
template = """
####
A__#
#_b#
####"""

[village_house_room.b]
size = [4, 4]
template = """
####
#_b#
A__#
####"""

[village_house_room.c]
size = [4, 4]
template = """
####
#b_#
#__B
####"""

[village_plaza]
[village_plaza.d]
size = [9, 9]
template = """
..+++++..
.++*+*++.
++*+++*++
+*+++++*+
++++&++++
+*+++++*+
++*+++*++
.++*+*++.
..+++++.."""


[village_cemetery]
[village_cemetery.d]
size = [15, 15]
template = """
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""