[symbols]
'-' = { ground= 6 }
'b' = { ground= 6, object= 13 }

[varningr_lair]

[varningr_lair.a]
size = [15, 15]
allow_flip_hor = true
allow_flip_ver = true
template = """
....-..........
...-b-.-.......
.----------....
..----------...
.------------..
.-------------.
..------------.
..-----------..
.------------..
.---------b---.
.-b----------..
..--....----...
...............
..--....-......
...-...........
"""

[varningr_lair.b]
size = [15, 15]
allow_flip_hor = true
allow_flip_ver = true
template = """
...............
...--...---....
..----.--b--...
..-b---------..
.------------..
.-----------...
..-----b-----..
...----------..
...---------...
..-----------..
..--b--------..
...--------....
.....---.......
...............
...............
"""